name: Release

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Application'
        required: true
        default: 'staging-tests-scripts'
        type: choice
        options:
          - staging-tests-scripts
      increment:
        description: 'Increment'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      environment:
        description: 'Environment'
        required: true
        default: 'STAGING'
        type: choice
        options:
          - LIVE
          - STAGING

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "App: $APP"
          echo "Increment: $INCREMENT"
          echo "Environment: $ENVIRONMENT"
        env:
          APP: ${{ inputs.app }}
          INCREMENT: ${{ inputs.increment }}
          ENVIRONMENT: ${{ inputs.environment }}
        if: ${{ inputs.environment }} == "LIVE"
